// src/utils/mailer.js
import nodemailer from "nodemailer";
import 'dotenv/config';

const filscapSignature = `
  <hr style="border:none; border-top:1px solid #dcdcdc; margin:20px 0;" />
  <p style="margin:0; font-weight:bold; color:#000000; font-size:14px;">FILSCAP Distribution Support Team</p>
  <p style="margin:2px 0; color:#00008b; font-size:13px;"><strong>Email Address:</strong> ddminquiry@filscap.com.ph</p>
  <p style="margin:2px 0; color:#00008b; font-size:13px;"><strong>Office Address:</strong> 140 Scout Rallos St., Brgy. Sacred Heart, Quezon City, Philippines</p>
  <br />
  <table cellpadding="0" cellspacing="0" border="0" style="border-collapse:collapse;">
    <tr>
      <td><a href="https://www.filscap.org"><img src="https://i.imgur.com/qaGTIOd.png" width="120" alt="FILSCAP"></a></td>
      <td width="12"></td>
      <td><a href="https://www.youtube.com/@filscap361"><img src="https://i.imgur.com/RLrsx0f.png" width="24" alt="YouTube"></a></td>
      <td width="6"></td>
      <td><a href="https://www.facebook.com/FILSCAP/"><img src="https://i.imgur.com/GAZ9Hao.png" width="24" alt="Facebook"></a></td>
      <td width="6"></td>
      <td><a href="https://www.instagram.com/filscap_/"><img src="https://i.imgur.com/UxtdyNQ.png" width="24" alt="Instagram"></a></td>
    </tr>
  </table>
  <br />
  <span style="color:#9b9b9b; font-size:13px;">
    This message serves as an official acknowledgment that your request has been successfully received and logged into the FILSCAP Distribution Support System for processing.
  </span>
  <br /><br />
  <span style="color:#00008b; font-size:10px;">
    This is an automated email generated by the FILSCAP Distribution Support System. 
    Please do not modify the subject line and reply only within this email thread.
  </span>
`;

const transporter = nodemailer.createTransport({
  host: "smtp.gmail.com",
  port: 465,
  secure: true,
  auth: {
    user: process.env.EMAIL_USER,
    pass: process.env.EMAIL_PASS,
  },
});

transporter.verify((error, success) => {
  if (error) {
    console.error("❌ Mailer Connection Error:", error);
  } else {
    console.log("✅ Mailer is connected and ready to send");
  }
});

export const sendBillingEmail = async (data) => {
  const mailOptions = {
    from: `"FILSCAP Revenue System" <${process.env.EMAIL_USER}>`,
    to: "alindao.michael02@gmail.com", 
    subject: `FOR BILLING: ${data.DSP} - ${data.Collection_ID}`,
    html: `
      <div style="font-family: Arial, sans-serif; max-width: 600px; padding: 20px; color: #333;">
        <h2 style="color: #004aad; border-bottom: 2px solid #004aad; padding-bottom: 10px;">New Billing Entry Detected</h2>
        <p>Hello Team,</p>
        <p>The following record has been marked as <span style="color: #d32f2f; font-weight: bold;">FOR BILLING</span>:</p>
        
        <table style="width: 100%; border-collapse: collapse; margin: 20px 0; background-color: #f9f9f9;">
          <tr>
            <td style="padding: 12px; border: 1px solid #ddd; font-weight: bold; width: 40%;">Collection ID:</td>
            <td style="padding: 12px; border: 1px solid #ddd;">${data.Collection_ID}</td>
          </tr>
          <tr>
            <td style="padding: 12px; border: 1px solid #ddd; font-weight: bold;">DSP / Source:</td>
            <td style="padding: 12px; border: 1px solid #ddd;">${data.DSP}</td>
          </tr>
          <tr>
            <td style="padding: 12px; border: 1px solid #ddd; font-weight: bold;">Amount:</td>
            <td style="padding: 12px; border: 1px solid #ddd; color: #004aad; font-weight: bold;">
              ${data.Currency} ${Number(data.Gross || 0).toLocaleString(undefined, { minimumFractionDigits: 2 })}
            </td>
          </tr>
          <tr>
            <td style="padding: 12px; border: 1px solid #ddd; font-weight: bold;">Processed By:</td>
            <td style="padding: 12px; border: 1px solid #ddd;">${data.userName || "System"}</td>
          </tr>
        </table>

        ${filscapSignature}
      </div>
    `,
  };

  try {
    await transporter.sendMail(mailOptions);
    console.log(`✅ Success: Email sent for ${data.Collection_ID}`);
  } catch (error) {
    console.error("❌ Nodemailer Error:", error);
  }
};